version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - redis
    
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   command: celery -A backend worker --loglevel=info
  #   depends_on:
  #     - redis
volumes:
  redis-data:
    driver: local