# Generated by Django 4.2.4 on 2023-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('BORRWOER', 'Borrwoer'), ('INVESTOR', 'Investor')], default='BORRWOER', max_length=250),
        ),
    ]
