# Generated by Django 4.2.4 on 2023-08-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='offer',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.loan'),
        ),
        migrations.AlterField(
            model_name='scheduledpayments',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
